# Generated by Django 5.2.12 on 2026-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("referral_code", models.CharField(blank=True, max_length=80)),
                ("utm_source", models.CharField(blank=True, max_length=120)),
                ("utm_medium", models.CharField(blank=True, max_length=120)),
                ("utm_campaign", models.CharField(blank=True, max_length=120)),
                ("landing_path", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
