# Generated by Django 5.2.12 on 2026-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrewingGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "product_handle",
                    models.CharField(
                        blank=True,
                        help_text="Shopify product handle this guide is associated with (optional).",
                        max_length=200,
                    ),
                ),
                (
                    "guide_type",
                    models.CharField(
                        choices=[
                            ("pour_over", "Pour-Over"),
                            ("french_press", "French Press"),
                            ("espresso_basics", "Espresso Basics"),
                            ("tea_steeping", "Tea Steeping"),
                            ("matcha_preparation", "Matcha Preparation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "audience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner-Friendly"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("is_premium_featured", models.BooleanField(default=False)),
                ("method", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                ("water_temp", models.CharField(blank=True, max_length=50)),
                ("brew_time", models.CharField(blank=True, max_length=50)),
                ("grind_size", models.CharField(blank=True, max_length=50)),
                ("ratio", models.CharField(blank=True, max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="guides/")),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TastingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, help_text="Product display name", max_length=200
                    ),
                ),
                (
                    "product_handle",
                    models.CharField(
                        blank=True,
                        help_text="Shopify product handle (slug) for linking to the product page.",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("aroma", models.CharField(blank=True, max_length=200)),
                ("flavor", models.CharField(blank=True, max_length=200)),
                ("finish", models.CharField(blank=True, max_length=200)),
                ("origin", models.CharField(blank=True, max_length=200)),
                ("pairings", models.CharField(blank=True, max_length=200)),
                ("style_notes", models.CharField(blank=True, max_length=200)),
                ("tags", models.CharField(blank=True, max_length=250)),
                ("rating", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrewGuide",
            fields=[],
            options={
                "verbose_name": "brew guide",
                "verbose_name_plural": "brew guides",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.brewingguide",),
        ),
    ]
